- alias: 'Turn on lights in morning'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: light.turn_on
    entity_id:
      - light.room_light
      - light.room_work_lights


- alias: 'Turn off lights in midnight'
  trigger:
    platform: time
    at: '00:15:00'
  action:
    service: light.turn_off
    entity_id:
      - light.room_light
      - light.room_work_lights

