- alias: Turn on lights in morning
  trigger:
    platform: time
    at: 08:45:00
  action:
    service: light.turn_on
    entity_id:
    - light.living_room_light
    - light.living_room_work_lights

- alias: Turn off lights in midnight
  trigger:
    platform: time
    at: 00:15:00
  action:
    service: light.turn_off
    entity_id:
    - light.living_room_light
    - light.living_room_work_lights

- action:
  - alias: Turn on room lights
    data:
      entity_id:
      - light.living_room_light
      - light.living_room_work_lights
    service: light.turn_on
  alias: Turn on room lights
  condition: []
  id: '1511381851678'
  trigger:
  - at: 06:30:00
    platform: time
